### ISSUE TITLE
command for sending entire buffer, or to send everything between two delimiters?

### ISSUE THREAD

**Issue by riatzukiza** [ffevotte/isend-mode.el#11]
this would be really neat for working with repls, I would set this up my self but I kinda suck with emacs lisp. I still might try, and would appriciate being pointed in the right direction at least.

**Comment by ffevotte** [comment]
When I need to send the entire buffer, I personally usually press
- <kbd>C-x</kbd><kbd>h</kbd> to select the whole buffer, then
- <kbd>C-RET</kbd> to send it.

Would this workflow suit you? Or would you still like to have a specific command for that?

As for sending everything between two delimiters, what would your use case be? You would define start & end delimiters on a per-buffer basis (or depending on the mode)? And what then? I can see at least two sensible behaviors:
1. you use the normal `isend-send` command (i.e. you press <kbd>C-RET</kbd> as usual), but the command is "smart" in the sense that if point is inbetween the start and end delimiters, the delimited section gets sent, **OR**
2. there is a new, specific command (and key binding) that looks around point for the start and end delimiters, and then sends the delimited section (or errors if point is not within the delimiters).

Is this what you had in mind? Or did you think about something else?

**Comment by riatzukiza** [comment]
I use a lot of lisp, but not nessisarily, common lisp or clojure. Most of these lisps do not have a *SLIME* type environment to work with, but slime really has more features than is needed for the basics.

I was actually going through the slime source code to figure out how they grabbed s-expressions and sent them to the inferior lisp process.

The most interesting one, is `eval-defun`, which despite its name, actually evaluates the top level form from the location you are at.

I don't think that it'd make sense to just steal the slime s-expression type way of doing this, as I also like to work with other languages with repls that are not lispy, eg javascript.

I've been thinking on this a few days now since I found this project, and I think the best way to do that genericly, in a way that *usually* works, is to search up and down from the current line until you find one that does not start with any white space characters, most languages don't have signifigant whitespace, but most the time you'd be insane to not use white space.

**Comment by ffevotte** [comment]
I pushed a few changes related to this in branch issue11

Two new commands are defined (and not bound by default, so that you should invoke them with <kbd>M-x</kbd>):
- `isend-send-buffer`: sends the entire buffer
- `isend-send-defun`: sends the current "defun"

A defun is defined by `isend-mark-defun-function` (which is by default `mark-defun` and is valid for LISP-like languages).
A Python-specific `isend--python-mark-defun` is shipped in the commit as well. It marks the current top-level python block.
I did not implement any indentation-based `mark-defun` function. But I guess your approach should work, especially for languages with "begin...end" blocks.

Please tell me if you can test this, and if it suits your needs.

**Comment by riatzukiza** [comment]
Awesome! I am going to pull this and try it out.

**Comment by riatzukiza** [comment]
yes, thank you, this works very well. I just tested this, both commands work as expected.

**Comment by ffevotte** [comment]
Thanks for testing... and for submitting the issue in the first place!
